### ISSUE TITLE
some question about the input and output of the LSTM

### ISSUE THREAD

**Issue by Ouya-Bytes** [kracwarlock/action-recognition-visual-attention#10]
Hello,Kracwarklock.I want to know is l(ti) reprensent a scalar?and what the shape of the x(t)=sum{l(ti)_X(t,i)},i=1....k_k,  x(t) is a vextor?a martix? or a cube?

**Comment by kracwarlock** [comment]
Hi @OuYag 

Yes `l_{t,i}` is a scalar. It represents the weight of the i-th location and the timestep-t for the attention model.

**Comment by kracwarlock** [comment]
For the paper:
x_t for a single data point is of shape (D,). We had D=1024 since we used googlenet features. It is a vector for a datapoint which is the average of the feature cube weighted by the location.

In the code:
Since we use batches, this becomes (batch_size,D) for each minibatch of examples. It is represented by the variable `ctx_` https://github.com/kracwarlock/action-recognition-visual-attention/blob/master/src/actrec.py#L278
